/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ford_gt.glb -T 
Files: ford_gt.glb [7.66MB] > /Users/oussemanijewi/Documents/portfolio/public/models/ford_gt-transformed.glb [966.56KB] (87%)
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2019-ford-gt-mkii-track-bffecac59a6b4bc49534be85b5b501c0
Title: 2019 Ford GT MKII Track
*/

import { useGLTF } from "@react-three/drei";

export function FordGt(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}models/ford_gt-transformed.glb`
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiiglass_detachable_glass_LOD2_UV2_Untitled_256_Default_glas_0
            .geometry
        }
        material={materials.PaletteMaterial001}
        position={[0, 0.02, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiiglass_detachable_details_LOD2_UV2_Untitled_051_Default_car_ford_gt_mkiiDefault1_0
            .geometry
        }
        material={materials.car_ford_gt_mkiiDefault1}
        position={[0, 0.02, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiidetach_wing_15_tiled_carbon_LOD2_UV2_Untitled_239_Default_carbon_0
            .geometry
        }
        material={materials.carbon}
        position={[0, 0.015, -0.041]}
        rotation={[0, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiidetach_door_R_90_stickers_red_LOD2_UV2_Untitled_172_Default_red_0
            .geometry
        }
        material={materials.PaletteMaterial002}
        position={[-0.005, 0, 0.024]}
        rotation={[1.062, -0.231, -2.75]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiidetach_door_R_90_stickers_black_LOD2_UV2_Untitled_266_Default_black_0
            .geometry
        }
        material={materials.PaletteMaterial003}
        position={[-0.005, 0, 0.024]}
        rotation={[1.062, -0.231, -2.75]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiichassis_licenseplate_LOD2_UV2_Untitled_263_Default_phong6_0
            .geometry
        }
        material={materials.PaletteMaterial004}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiichassis_underside_LOD2_UV2_Untitled_249_Default_under_0
            .geometry
        }
        material={materials.under}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiiwheelFR_caliper_calipers_garage_LOD2_UV2_Untitled_267_Default_calip_0
            .geometry
        }
        material={materials.calip}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiiwheelFR_tire_tires_LOD2_UV2_Untitled_229_Default_tyre_0
            .geometry
        }
        material={materials.tyre}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .car_ford_gt_mkiidetach_wing_15_carpaint_LOD2_UV2_Untitled_183_Default_carpaint_0
            .geometry
        }
        material={materials.PaletteMaterial005}
        position={[0, 0.015, -0.041]}
        rotation={[0, 0, Math.PI]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/ford_gt-transformed.glb`);
