/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 oculus_quest_2.glb -T 
Files: oculus_quest_2.glb [21.98MB] > /Users/oussemanijewi/Documents/portfolio/public/models/oculus_quest_2-transformed.glb [1.8MB] (92%)
Author: NosTeam (https://sketchfab.com/NosTeam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oculus-quest-2-c6a1c2623d224a1bbb81a38915f7e898
Title: Oculus quest 2
*/

import { useGLTF } from "@react-three/drei";

export function VrHeadset(props) {
  const { nodes, materials } = useGLTF(
    "/models/oculus_quest_2-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Controllers_Controllers_0.geometry}
        material={materials.Controllers}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.333}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Oculus_Headset_Headset_0.geometry}
        material={materials.Headset}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.333}
      />
    </group>
  );
}

useGLTF.preload("/models/oculus_quest_2-transformed.glb");
